version: 2

python:
  install:
    - requirements: docs/requirements.txt
    
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    install:
      - pip install GeometricConvolutions/.

mkdocs:
  configuration: mkdocs.yml