site_name: GI-Net
site_description: Equivariant geometric convolutions for vector or tensor images
site_author: Wilson Gregory
repo_url: https://github.com/WilsonGregory/GeometricConvolutions
repo_name: WilsonGregory/GeometricConvolutions

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - API: reference.md
theme: readthedocs  

plugins:
  - search  # default search plugin; needs manually re-enabling when using any other plugins
  - mkdocstrings:
        handlers:
            python:
                options:
                    inherited_members: true  # Allow looking up inherited methods
                    show_root_heading: true  # actually display anything at all...
                    show_root_full_path: true  # display "diffrax.asdf" not just "asdf"
                    show_if_no_docstring: true
                    show_signature_annotations: true
                    show_source: false  # don't include source code
                    members_order: source  # order methods according to their order of definition in the source code, not alphabetical order
                    heading_level: 4